/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
 package loginandregister;
 import javax.swing.table.DefaultTableModel;
 import java.util.List;
 import javax.swing.JOptionPane;
 import data.EmployeeDAO;
/**
 *
 * @author Claire
 */
public class AdminPage extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        
    }

    
    
    
    
public void loadEmployeeData() {
    String[] columnNames = {"ID", "Last Name", "First Name", "Birthday", "Address", "Phone Number", 
        "SSS #", "Philhealth #", "TIN #", "Pag-ibig #", "Status", "Position", "Immediate Supervisor", 
        "Basic Salary", "Rice Subsidy", "Phone Allowance", "Clothing Allowance", 
        "Gross Semi-monthly Rate", "Hourly Rate"};

    DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // This causes all cells to be uneditable
        }
    };

    try {
        EmployeeDAO dao = new EmployeeDAO();
        List<data.Employee> employees = dao.findAll();
        
        if (employees == null || employees.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No employee records found.", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        for (data.Employee e : employees) {
            if (e != null) {
                String[] row = new String[] {
                    e.getEmployeeId() != null ? e.getEmployeeId() : "",
                    e.getLastName() != null ? e.getLastName() : "",
                    e.getFirstName() != null ? e.getFirstName() : "",
                    e.getBirthday() != null ? e.getBirthday() : "",
                    e.getAddress() != null ? e.getAddress() : "",
                    e.getPhoneNumber() != null ? e.getPhoneNumber() : "",
                    e.getSssNumber() != null ? e.getSssNumber() : "",
                    e.getPhilhealthNumber() != null ? e.getPhilhealthNumber() : "",
                    e.getTinNumber() != null ? e.getTinNumber() : "",
                    e.getPagIbigNumber() != null ? e.getPagIbigNumber() : "",
                    e.getStatus() != null ? e.getStatus() : "",
                    e.getPosition() != null ? e.getPosition() : "",
                    e.getImmediateSupervisor() != null ? e.getImmediateSupervisor() : "",
                    e.getBasicSalary() != null ? e.getBasicSalary() : "",
                    e.getRiceSubsidy() != null ? e.getRiceSubsidy() : "",
                    e.getPhoneAllowance() != null ? e.getPhoneAllowance() : "",
                    e.getClothingAllowance() != null ? e.getClothingAllowance() : "",
                    e.getGrossSemiMonthlyRate() != null ? e.getGrossSemiMonthlyRate() : "",
                    e.getHourlyRate() != null ? e.getHourlyRate() : ""
                };
                model.addRow(row);
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Database error: " + ex.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
            "An unexpected error occurred: " + ex.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

    jTableDataBase.setModel(model);
}
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCreateRec = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonEditRec = new javax.swing.JButton();
        jButtonDeleteRec = new javax.swing.JButton();
        jTextFieldPosition = new javax.swing.JTextField();
        jTextFieldEmpNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonViewAllEmp = new javax.swing.JButton();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldPhoneNum = new javax.swing.JTextField();
        jTextFieldSupervisor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataBase = new javax.swing.JTable();
        jButtonViewEmp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonLogout = new javax.swing.JButton();
        jButtonLeaveManagement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCreateRec.setText("Create Employee");
        jButtonCreateRec.setEnabled(false);
        jButtonCreateRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCreateRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 130, 30));

        jButtonClear.setText("Clear Employee");
        jButtonClear.setEnabled(false);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 130, 30));

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.setEnabled(false);
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 130, 30));

        jButtonEditRec.setText("Edit Employee");
        jButtonEditRec.setEnabled(false);
        jButtonEditRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 130, 30));

        jButtonDeleteRec.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDeleteRec.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteRec.setText("Delete Employee");
        jButtonDeleteRec.setEnabled(false);
        jButtonDeleteRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeleteRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 130, 30));

        jTextFieldPosition.setEditable(false);
        jTextFieldPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPositionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 250, 30));

        jTextFieldEmpNum.setEditable(false);
        jPanel1.add(jTextFieldEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 70, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee Number: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("First Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone No.:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Supervisor:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 70, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 50, 20));

        jButtonViewAllEmp.setText("View All Employees");
        jButtonViewAllEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllEmpActionPerformed(evt);
                onViewAllEmployeesClick(evt);
            }
        });
        jPanel1.add(jButtonViewAllEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 220, 40));

        jTextFieldLastName.setEditable(false);
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, 30));

        jTextFieldFirstName.setEditable(false);
        jTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 250, 30));

        jTextFieldPhoneNum.setEditable(false);
        jTextFieldPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNumActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 250, 30));

        jTextFieldSupervisor.setEditable(false);
        jTextFieldSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 250, 30));

        jTableDataBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDataBase.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableDataBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDataBaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDataBase);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 820, 530));

        jButtonViewEmp.setText("View Employee Details");
        jButtonViewEmp.setEnabled(false);
        jButtonViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewEmpActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonViewEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 130, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 50, 30));

        jTextFieldStatus.setEditable(false);
        jTextFieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStatusActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 250, 30));

        jTextAreaAddress.setEditable(false);
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 250, 40));

        jButtonLogout.setBackground(new java.awt.Color(0, 255, 204));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        jButtonLeaveManagement.setBackground(new java.awt.Color(255, 51, 51));
        jButtonLeaveManagement.setText("Leave Management");
        jButtonLeaveManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveManagementActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLeaveManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -6, 1320, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateRecActionPerformed
     CreateEmployee createEmployee = new CreateEmployee();
     createEmployee.setVisible(true);


    }//GEN-LAST:event_jButtonCreateRecActionPerformed

    private void jButtonEditRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditRecActionPerformed
        // TODO add your handling code here:
        
        
      DefaultTableModel model = (DefaultTableModel) jTableDataBase.getModel();
        int selectedRowIndex = jTableDataBase.getSelectedRow();
       if(selectedRowIndex!=-1)
       {
           loginandregister.Employee employee = new loginandregister.Employee();
           employee.setEmployeeID(jTextFieldEmpNum.getText()); 
           EditEmployee editEmployee = new EditEmployee(employee);
          editEmployee.setVisible(true);
       }
               
        
    }//GEN-LAST:event_jButtonEditRecActionPerformed

    private void jButtonDeleteRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRecActionPerformed
        String id = jTextFieldEmpNum.getText();
        if (id == null || id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a record first.");
            return;
        }
        try {
            EmployeeDAO dao = new EmployeeDAO();
            boolean ok = dao.delete(id);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
                loadEmployeeData(null);
                jButtonDeleteRec.setEnabled(false);
                jButtonEditRec.setEnabled(false);
                jButtonViewEmp.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "No record deleted (not found).");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteRecActionPerformed

    private void jTextFieldPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPositionActionPerformed

    private void jButtonViewAllEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllEmpActionPerformed
       loadEmployeeData(null);
    }//GEN-LAST:event_jButtonViewAllEmpActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstNameActionPerformed

    private void jTextFieldPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumActionPerformed

    private void jTextFieldSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupervisorActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jButtonDeleteRec.setEnabled(false);
        jButtonEditRec.setEnabled(false);
        jButtonViewEmp.setEnabled(false);
        
        
        jTextFieldEmpNum.setText("");
         jTextFieldLastName.setText("");
         jTextFieldFirstName.setText("");
         jTextAreaAddress.setText("");
         jTextFieldPhoneNum.setText("");
         jTextFieldSupervisor.setText("");
         jTextFieldPosition.setText("");
         jTextFieldStatus.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        // temporary
        this.setVisible(false);
        Login login = new Login();
         login.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jTableDataBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDataBaseMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableDataBase.getModel();
        int SelectedRowIndex = jTableDataBase.getSelectedRow();
        
         jTextFieldEmpNum.setText(model.getValueAt(SelectedRowIndex, 0).toString());
         jTextFieldLastName.setText(model.getValueAt(SelectedRowIndex, 1).toString());
         jTextFieldFirstName.setText(model.getValueAt(SelectedRowIndex, 2).toString());
         jTextAreaAddress.setText(model.getValueAt(SelectedRowIndex, 4).toString());
         jTextFieldPhoneNum.setText(model.getValueAt(SelectedRowIndex, 5).toString());
         jTextFieldSupervisor.setText(model.getValueAt(SelectedRowIndex, 12).toString());
         jTextFieldPosition.setText(model.getValueAt(SelectedRowIndex, 11).toString());
         jTextFieldStatus.setText(model.getValueAt(SelectedRowIndex, 10).toString());
         
         jButtonDeleteRec.setEnabled(true);
         jButtonEditRec.setEnabled(true);
         jButtonClear.setEnabled(true);
         jButtonViewEmp.setEnabled(true);
    }//GEN-LAST:event_jTableDataBaseMouseClicked

    private void jButtonViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewEmpActionPerformed
        UserAccount user = new UserAccount();
        user.setEmployeeID(jTextFieldEmpNum.getText());
       

        this.setVisible(false);
        ViewEmployee viewEmployee;
        viewEmployee = new ViewEmployee(user);
        viewEmployee.setVisible(true);
    }//GEN-LAST:event_jButtonViewEmpActionPerformed

    private void jTextFieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStatusActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
       loadEmployeeData(null);
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void onViewAllEmployeesClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onViewAllEmployeesClick
        // TODO add your handling code here:
        jButtonCreateRec.setEnabled(true);
        

        jButtonRefresh.setEnabled(true);
        
    }//GEN-LAST:event_onViewAllEmployeesClick

    private void jButtonLeaveManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveManagementActionPerformed
        ViewLeaveManagement leaveManagement = new ViewLeaveManagement();
        this.setVisible(false);
        leaveManagement.setVisible(true);
    }//GEN-LAST:event_jButtonLeaveManagementActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCreateRec;
    private javax.swing.JButton jButtonDeleteRec;
    private javax.swing.JButton jButtonEditRec;
    private javax.swing.JButton jButtonLeaveManagement;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonViewAllEmp;
    private javax.swing.JButton jButtonViewEmp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDataBase;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmpNum;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhoneNum;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldSupervisor;
    // End of variables declaration//GEN-END:variables
}
