 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregister;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import data.EmployeeDAO;
import data.Employee;
/**
 *
 * @author Claire
 */

public class EditEmployee extends javax.swing.JFrame {
    String employeeID;
    /**
     * Creates new form EmployeeDisplayInformation
     */
    
    
    public EditEmployee(loginandregister.Employee employee) {
        initComponents();
        
        employeeID = employee.getEmployeeID();
        try {
            EmployeeDAO dao = new EmployeeDAO();
            Employee de = dao.findById(employeeID);
            if (de == null) {
                JOptionPane.showMessageDialog(this, "Employee not found in database.");
                this.setVisible(false);
                return;
            }
            jTextFieldEmpNum1.setText(de.getEmployeeId());
            jTextFieldFirstName1.setText(de.getFirstName());
            jTextFieldLastName1.setText(de.getLastName());
            jTextFieldAddress.setText(de.getAddress());
            String birthday = de.getBirthday();
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            Date birthdayDate;
            try {
                birthdayDate = sdf.parse(birthday);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Error parsing birthday: " + e.getMessage());
                return;
            }
            jCalendarBirthday1.setDate(birthdayDate);
            jCalendarBirthday1.repaint();
            jTextFieldPhoneNum1.setText(de.getPhoneNumber());
            jTextFieldSSSNum1.setText(de.getSssNumber());
            jTextFieldPhilHealthNum1.setText(de.getPhilhealthNumber());
            jTextFieldTINNum1.setText(de.getTinNumber());
            jTextFieldPagibigNum1.setText(de.getPagIbigNumber());
            jComboBoxStatus1.setSelectedItem(de.getStatus());
            jComboBoxPosition1.setSelectedItem(de.getPosition());
            jComboBoxSupervisor1.setSelectedItem(de.getImmediateSupervisor());
            jTextFieldBasicSalary1.setText(de.getBasicSalary());
            jTextFieldRiceSubsidy1.setText(de.getRiceSubsidy());
            jTextFieldPhoneAllowance1.setText(de.getPhoneAllowance());
            jTextFieldClothingAllowance1.setText(de.getClothingAllowance());
            jTextFieldGrossSemiMonthly1.setText(de.getGrossSemiMonthlyRate());
            jTextFieldHourlyRate1.setText(de.getHourlyRate());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }

        
        
        

  
     
      
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmpNum1 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jComboBoxPosition1 = new javax.swing.JComboBox<>();
        jComboBoxStatus1 = new javax.swing.JComboBox<>();
        jComboBoxSupervisor1 = new javax.swing.JComboBox<>();
        jPanel19 = new javax.swing.JPanel();
        jTextFieldPhilHealthNum1 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jTextFieldSSSNum1 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextFieldTINNum1 = new javax.swing.JTextField();
        jTextFieldPagibigNum1 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPhoneNum1 = new javax.swing.JTextField();
        jTextFieldLastName1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jTextFieldFirstName1 = new javax.swing.JTextField();
        jCalendarBirthday1 = new com.toedter.calendar.JCalendar();
        jPanel21 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jTextFieldPhoneAllowance1 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jTextFieldClothingAllowance1 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jTextFieldRiceSubsidy1 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jTextFieldHourlyRate1 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jTextFieldBasicSalary1 = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jTextFieldGrossSemiMonthly1 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jButtonSave1 = new javax.swing.JButton();
        jButtonCancel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(0, 255, 204));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setText("MotorPH");
        jPanel17.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -10, 160, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Payroll System");
        jPanel17.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Employee Number");
        jPanel17.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 20));

        jTextFieldEmpNum1.setEditable(false);
        jTextFieldEmpNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpNum1ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextFieldEmpNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, -1));

        getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 120));

        jPanel18.setBackground(new java.awt.Color(0, 255, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setText("Employment Details");
        jPanel18.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("Position");
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 20));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setText("Status");
        jPanel18.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 20));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("Supervisor");
        jPanel18.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 20));

        jComboBoxPosition1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chief Executive Officer", "Chief Operating Officer", "Chief Finance Officer", "Chief Marketing Officer", "Account Manager", "IT Operations and Systems", "HR Manager", "Accounting Head", "Sales & Marketing", "Supply Chain and Logistics", "Customer Service and Relations", "Payroll Manager", "HR Team Leader", "Account Team Leader", "Payroll Team Leader", "Account Rank and File", "Payroll Rank and File", "HR Rank and File" }));
        jComboBoxPosition1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPosition1ActionPerformed(evt);
            }
        });
        jPanel18.add(jComboBoxPosition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, -1));

        jComboBoxStatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Probationary", " " }));
        jPanel18.add(jComboBoxStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, -1));

        jComboBoxSupervisor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Garcia Manuel III", "Lim Antonio", "Aquino Bianca Sofia", "Reyes Isabella", "Alvaro Roderick", "Villanueva Andrea Mae", "Romualdez Fredrick", "Salcedo Anthony", "De Leon Selena", "Mata Christian", "San Jose Brad" }));
        jPanel18.add(jComboBoxSupervisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, -1));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 480, 230));

        jPanel19.setBackground(new java.awt.Color(0, 255, 204));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel19.add(jTextFieldPhilHealthNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel61.setText("Government Identifiers");
        jPanel19.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel62.setText("PhilHealth");
        jPanel19.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, 20));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel63.setText("SSS Number");
        jPanel19.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 20));
        jPanel19.add(jTextFieldSSSNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 160, -1));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel64.setText("TIN Number");
        jPanel19.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 20));
        jPanel19.add(jTextFieldTINNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 160, -1));
        jPanel19.add(jTextFieldPagibigNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 160, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setText("Pag-IBIG Number");
        jPanel19.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 20));

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 540, 230));

        jPanel20.setBackground(new java.awt.Color(0, 255, 204));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Address");
        jPanel20.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Phone Number");
        jPanel20.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 20));
        jPanel20.add(jTextFieldPhoneNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 210, -1));
        jPanel20.add(jTextFieldLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 210, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Employee Information");
        jPanel20.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 20));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("Last Name");
        jPanel20.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, 20));
        jPanel20.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 210, 20));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel67.setText("Birth Day");
        jPanel20.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel68.setText("First Name");
        jPanel20.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 20));

        jTextFieldFirstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstName1ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextFieldFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, -1));

        jCalendarBirthday1.setBackground(new java.awt.Color(0, 255, 204));
        jCalendarBirthday1.setForeground(new java.awt.Color(0, 255, 204));
        jCalendarBirthday1.setSundayForeground(new java.awt.Color(255, 51, 51));
        jPanel20.add(jCalendarBirthday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 110));

        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 480, 350));

        jPanel21.setBackground(new java.awt.Color(0, 255, 204));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel69.setText("Salary Details");
        jPanel21.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 20));
        jPanel21.add(jTextFieldPhoneAllowance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 110, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel70.setText("Phone Allowance");
        jPanel21.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel71.setText("Clothing Allowance");
        jPanel21.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));
        jPanel21.add(jTextFieldClothingAllowance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 110, -1));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel72.setText("Rice Subsidy");
        jPanel21.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));
        jPanel21.add(jTextFieldRiceSubsidy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 110, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel73.setText("Hourly Rate");
        jPanel21.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));
        jPanel21.add(jTextFieldHourlyRate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 110, -1));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel74.setText("Gross Semi-Monthly");
        jPanel21.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 20));
        jPanel21.add(jTextFieldBasicSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 110, -1));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel75.setText("Basic Salary");
        jPanel21.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, 20));
        jPanel21.add(jTextFieldGrossSemiMonthly1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 110, -1));

        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 540, 260));

        jPanel22.setBackground(new java.awt.Color(0, 255, 204));

        jButtonSave1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSave1.setText("Save");
        jButtonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave1ActionPerformed(evt);
            }
        });

        jButtonCancel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancel1.setText("Cancel");
        jButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jButtonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave1)
                    .addComponent(jButtonCancel1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 540, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmpNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpNum1ActionPerformed

    private void jComboBoxPosition1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPosition1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPosition1ActionPerformed

    private void jTextFieldFirstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstName1ActionPerformed

    private void jButtonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave1ActionPerformed
        // Validate, then update employee in DB
        if (jTextFieldFirstName1.getText().trim().isEmpty() ||
            jTextFieldLastName1.getText().trim().isEmpty() ||
            jTextFieldAddress.getText().trim().isEmpty() ||
            jTextFieldPhoneNum1.getText().trim().isEmpty() ||
            jTextFieldSSSNum1.getText().trim().isEmpty() ||
            jTextFieldPhilHealthNum1.getText().trim().isEmpty() ||
            jTextFieldTINNum1.getText().trim().isEmpty() ||
            jTextFieldPagibigNum1.getText().trim().isEmpty() ||
            jTextFieldBasicSalary1.getText().trim().isEmpty() ||
            jTextFieldRiceSubsidy1.getText().trim().isEmpty() ||
            jTextFieldPhoneAllowance1.getText().trim().isEmpty() ||
            jTextFieldClothingAllowance1.getText().trim().isEmpty() ||
            jTextFieldGrossSemiMonthly1.getText().trim().isEmpty() ||
            jTextFieldHourlyRate1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please fill in all fields");
            return;
        }

        Validator validator = new Validator();
        if (!validator.isValidString(jTextFieldLastName1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please input valid Last Name");
            return;
        }
        if (!validator.isValidString(jTextFieldFirstName1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please input valid First Name");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        String birthday = sdf.format(jCalendarBirthday1.getDate());
        if (!validator.isValidAddress(jTextFieldAddress.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please exclude using commas in Address");
            return;
        }
        if (!validator.isValidPhoneNumber(jTextFieldPhoneNum1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please input valid Phone Number (xxx-xxx-xxx)");
            return;
        }
        if (!validator.isValidSssNumber(jTextFieldSSSNum1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please format SSS as xx-xxxxxxx-x");
            return;
        }
        if (!validator.isValidPhilhealthNumber(jTextFieldPhilHealthNum1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please format PhilHealth as xxxxxxxxxxxx (12 digits)");
            return;
        }
        if (!validator.isValidTin(jTextFieldTINNum1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please format TIN as xxx-xxx-xxx-xxx");
            return;
        }
        if (!validator.isValidPagibigNumber(jTextFieldPagibigNum1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please format Pagibig as xxxxxxxxxxxx (12 digits)");
            return;
        }
        if (!validator.isValidNumber(jTextFieldBasicSalary1.getText()) ||
            !validator.isValidNumber(jTextFieldRiceSubsidy1.getText()) ||
            !validator.isValidNumber(jTextFieldPhoneAllowance1.getText()) ||
            !validator.isValidNumber(jTextFieldClothingAllowance1.getText()) ||
            !validator.isValidNumber(jTextFieldGrossSemiMonthly1.getText()) ||
            !validator.isValidNumber(jTextFieldHourlyRate1.getText())) {
            JOptionPane.showMessageDialog(jButtonSave1, "Please input valid numeric values for salary fields");
            return;
        }

        try {
            Employee e = new Employee();
            e.setEmployeeId(jTextFieldEmpNum1.getText());
            e.setLastName(jTextFieldLastName1.getText());
            e.setFirstName(jTextFieldFirstName1.getText());
            e.setBirthday(birthday);
            e.setAddress(jTextFieldAddress.getText());
            e.setPhoneNumber(jTextFieldPhoneNum1.getText());
            e.setSssNumber(jTextFieldSSSNum1.getText());
            e.setPhilhealthNumber(jTextFieldPhilHealthNum1.getText());
            e.setTinNumber(jTextFieldTINNum1.getText());
            e.setPagIbigNumber(jTextFieldPagibigNum1.getText());
            e.setStatus((String) jComboBoxStatus1.getSelectedItem());
            e.setPosition((String) jComboBoxPosition1.getSelectedItem());
            e.setImmediateSupervisor((String) jComboBoxSupervisor1.getSelectedItem());
            e.setBasicSalary(jTextFieldBasicSalary1.getText());
            e.setRiceSubsidy(jTextFieldRiceSubsidy1.getText());
            e.setPhoneAllowance(jTextFieldPhoneAllowance1.getText());
            e.setClothingAllowance(jTextFieldClothingAllowance1.getText());
            e.setGrossSemiMonthlyRate(jTextFieldGrossSemiMonthly1.getText());
            e.setHourlyRate(jTextFieldHourlyRate1.getText());

            EmployeeDAO dao = new EmployeeDAO();
            boolean ok = dao.update(e);
            if (ok) {
                JOptionPane.showMessageDialog(jButtonSave1, "Updated Successfully\nPlease click Refresh to view changes.");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(jButtonSave1, "No changes saved.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(jButtonSave1, "Database error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSave1ActionPerformed

    private void jButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditEmployee().setVisible(true);
//            }
//        });
//    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonSave1;
    private com.toedter.calendar.JCalendar jCalendarBirthday1;
    private javax.swing.JComboBox<String> jComboBoxPosition1;
    private javax.swing.JComboBox<String> jComboBoxStatus1;
    private javax.swing.JComboBox<String> jComboBoxSupervisor1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBasicSalary1;
    private javax.swing.JTextField jTextFieldClothingAllowance1;
    private javax.swing.JTextField jTextFieldEmpNum1;
    private javax.swing.JTextField jTextFieldFirstName1;
    private javax.swing.JTextField jTextFieldGrossSemiMonthly1;
    private javax.swing.JTextField jTextFieldHourlyRate1;
    private javax.swing.JTextField jTextFieldLastName1;
    private javax.swing.JTextField jTextFieldPagibigNum1;
    private javax.swing.JTextField jTextFieldPhilHealthNum1;
    private javax.swing.JTextField jTextFieldPhoneAllowance1;
    private javax.swing.JTextField jTextFieldPhoneNum1;
    private javax.swing.JTextField jTextFieldRiceSubsidy1;
    private javax.swing.JTextField jTextFieldSSSNum1;
    private javax.swing.JTextField jTextFieldTINNum1;
    // End of variables declaration//GEN-END:variables
}
