/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregister;

import ui.NeonBorderPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Claire
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // Set the default close operation and window title
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kharl Motor PH - Home");
        setMinimumSize(new java.awt.Dimension(900, 600));
        
        // Create main container with NeonBorderPanel
        NeonBorderPanel neonPanel = new NeonBorderPanel();
        neonPanel.setLayout(new BorderLayout());
        neonPanel.setBorder(new EmptyBorder(10, 10, 10, 10));
        
        jPanelRoot = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g.create();
                int w = getWidth();
                int h = getHeight();
                GradientPaint gp = new GradientPaint(0, 0, new Color(20, 30, 40), 0, h, new Color(10, 15, 25));
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, w, h);
                g2d.dispose();
            }
        };
        jPanelRoot.setLayout(new BorderLayout());
        jPanelRoot.setOpaque(false);
        
        neonPanel.add(jPanelRoot, BorderLayout.CENTER);
        
        // Header Panel with gradient
        jPanelHeader = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2d = (Graphics2D) g;
                int w = getWidth();
                int h = getHeight();
                GradientPaint gp = new GradientPaint(0, 0, new Color(0, 153, 153, 200), 0, h, new Color(0, 100, 100, 200));
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, w, h);
            }
        };
        jPanelHeader.setOpaque(false);
        jPanelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));
        
        jLabelTitle = new javax.swing.JLabel();
        jLabelSubtitle = new javax.swing.JLabel();
        
        // Body Panel
        jPanelBody = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(new Color(255, 255, 255, 10));
                g.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
            }
        };
        jPanelBody.setOpaque(false);
        btnEmployee = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnPayroll = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelRoot.setBackground(new java.awt.Color(245, 247, 250));
        jPanelRoot.setLayout(new java.awt.BorderLayout());

        jPanelHeader.setBackground(new java.awt.Color(0, 153, 153));
        jPanelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanelHeader.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("MotorPH");
        jPanelHeader.add(jLabelTitle, java.awt.BorderLayout.NORTH);

        jLabelSubtitle.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabelSubtitle.setForeground(new java.awt.Color(224, 255, 255));
        jLabelSubtitle.setText("Payroll System Dashboard");
        jPanelHeader.add(jLabelSubtitle, java.awt.BorderLayout.SOUTH);

        jPanelBody.setBackground(new java.awt.Color(245, 247, 250));
        jPanelBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanelBody.setLayout(new java.awt.GridLayout(2, 3, 20, 20));

        btnEmployee.setBackground(new java.awt.Color(0, 204, 204));
        btnEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnEmployee.setText("Employee Login");
        btnEmployee.setFocusPainted(false);
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        jPanelBody.add(btnEmployee);

        btnAdmin.setBackground(new java.awt.Color(0, 204, 204));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnAdmin.setText("Admin Dashboard");
        btnAdmin.setFocusPainted(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanelBody.add(btnAdmin);

        btnAttendance.setBackground(new java.awt.Color(238, 238, 238));
        btnAttendance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAttendance.setText("Attendance");
        btnAttendance.setFocusPainted(false);
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        jPanelBody.add(btnAttendance);

        btnPayroll.setBackground(new java.awt.Color(238, 238, 238));
        btnPayroll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPayroll.setText("Payroll Runs");
        btnPayroll.setFocusPainted(false);
        btnPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayrollActionPerformed(evt);
            }
        });
        jPanelBody.add(btnPayroll);

        btnReports.setBackground(new java.awt.Color(238, 238, 238));
        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReports.setText("Reports");
        btnReports.setFocusPainted(false);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        jPanelBody.add(btnReports);

        btnExit.setBackground(new java.awt.Color(255, 102, 102));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFocusPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanelBody.add(btnExit);

        jPanelRoot.add(jPanelHeader, java.awt.BorderLayout.NORTH);
        jPanelRoot.add(jPanelBody, java.awt.BorderLayout.CENTER);

        // Set the neon panel as content pane
        setContentPane(neonPanel);
        
        // Set window to be centered on screen
        setLocationRelativeTo(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        this.setVisible(false);
        new AdminPage().setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        this.setVisible(false);
        new AttendancePage().setVisible(true);
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayrollActionPerformed
        this.setVisible(false);
        new PayrollRunsPage().setVisible(true);
    }//GEN-LAST:event_btnPayrollActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        this.setVisible(false);
        new ReportsPage().setVisible(true);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomePage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPayroll;
    private javax.swing.JButton btnReports;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelRoot;
    
    // End of variables declaration//GEN-END:variables
}
