/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregister;
import com.opencsv.CSVWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Aira Joie Piopongco
 */
public class ViewLeaveManagement extends javax.swing.JFrame {
  private EmployeeCSVReader reader = new EmployeeCSVReader("LeaveManagement.csv");
  private List<String[]> leaveDataBase = reader.getEmployeeData();
  private String[] employeeData;
  
    /**
     * Creates new form ViewLeaveManagement
     */
    public ViewLeaveManagement() {
        String[] employeeData = new String[0];
        initComponents();
        loadLeaveData("LeaveManagement.csv");
    }

   public void loadLeaveData(String csvFile) {
    EmployeeCSVReader csvReader = new EmployeeCSVReader(csvFile);
    List<String[]> employeeData = csvReader.getEmployeeData();

  String[] columnNames = {"Request #", "ID", "Last Name","First Name","Department","Leave Type","Start Date","End Date","Status"};

            DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // This causes all cells to be uneditable
                }
            };

            // Add existing data to the model
            for (String[] row : employeeData) {
                model.addRow(row);
            }



            jTable.setModel(model);
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();
        jButtonApprove = new javax.swing.JButton();
        jButtonReject1 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(1312, 624));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Leave Management");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 70));

        jTable.setBackground(new java.awt.Color(0, 0, 0));
        jTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable.setForeground(new java.awt.Color(255, 255, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1140, 550));

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 170, 40));

        jButtonApprove.setBackground(new java.awt.Color(0, 255, 204));
        jButtonApprove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonApprove.setForeground(new java.awt.Color(255, 255, 255));
        jButtonApprove.setText("Approve");
        jButtonApprove.setEnabled(false);
        jButtonApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApproveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 70, 150, 50));

        jButtonReject1.setBackground(new java.awt.Color(204, 0, 0));
        jButtonReject1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReject1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReject1.setText("Reject");
        jButtonReject1.setEnabled(false);
        jButtonReject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReject1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 130, 150, 50));

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 580, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        loadLeaveData("LeaveManagement.csv");
         jButtonApprove.setEnabled(false);
         jButtonReject1.setEnabled(false);
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
      AdminPage AdminPage = new AdminPage();
      this.setVisible(false);
      AdminPage.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApproveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int SelectedRowIndex = jTable.getSelectedRow();
        String employeeID = model.getValueAt(SelectedRowIndex, 0).toString();      
               
       //change ID here 
        employeeData = reader.searchEmployee(employeeID);
            if (employeeData != null) {
                leaveDataBase = reader.getEmployeeData();
                employeeData[8] = "Approved";
                
             
            JOptionPane.showMessageDialog(this, "Request Approved Succesfully\nPlease refresh to see changes");
    } else {
        // handle the case where employeeData is null
        JOptionPane.showMessageDialog(this, "Employee not found!");
    } 
        try {
        CSVWriter writer = new CSVWriter(new FileWriter("LeaveManagement.csv"), ',', CSVWriter.NO_QUOTE_CHARACTER);

        for (String[] updatedRecord : leaveDataBase) {
            writer.writeNext(updatedRecord);
        }
        writer.close();
    } catch (IOException e) {
        // ignore exception for now
    }
        
        
    }//GEN-LAST:event_jButtonApproveActionPerformed

    private void jButtonReject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReject1ActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int SelectedRowIndex = jTable.getSelectedRow();
        String employeeID = model.getValueAt(SelectedRowIndex, 0).toString();      
               
        
        employeeData = reader.searchEmployee(employeeID);
            if (employeeData != null) {
                leaveDataBase = reader.getEmployeeData();
                employeeData[8] = "Denied";
                
             
            JOptionPane.showMessageDialog(this, "Request Denied Succesfully\nPlease refresh to see changes");
    } else {
        // handle the case where employeeData is null
        JOptionPane.showMessageDialog(this, "Employee not found!");
    } 
        try {
        CSVWriter writer = new CSVWriter(new FileWriter("LeaveManagement.csv"), ',', CSVWriter.NO_QUOTE_CHARACTER);

        for (String[] updatedRecord : leaveDataBase) {
            writer.writeNext(updatedRecord);
        }
        writer.close();
    } catch (IOException e) {
        // ignore exception for now
    }
        
    }//GEN-LAST:event_jButtonReject1ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        jButtonApprove.setEnabled(true);
        jButtonReject1.setEnabled(true);
        
        
    }//GEN-LAST:event_jTableMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewLeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewLeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewLeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewLeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewLeaveManagement().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApprove;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonReject1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
