/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.EmployeeManagement;

import Model.SalaryDeduction;
import Model.UserAccount;
import Model.Employee;
import Model.TotalPay;
import Model.WithholdingTax;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import loginandregister.EmployeeCSVReader;
import loginandregister.LeaveRequestForm;
import loginandregister.Login;

public class ViewEmployee extends javax.swing.JFrame {
   
    private EmployeeCSVReader reader;
    /**
     * Creates new form ViewEmployee
     */
    public ViewEmployee(UserAccount userAcc) {
        initComponents();
        
        reader = new EmployeeCSVReader("MotorPH.csv");
        String employeeID = userAcc.getEmployeeID();
        String[] employeeData = reader.searchEmployee(employeeID);
        
        if (employeeData == null) {
            JOptionPane.showMessageDialog(this, "Employee not found!");
            return; // stop loading the form
        }
        
        boolean isNewEmployee = (employeeData[13] == null || employeeData[13].trim().isEmpty()); // Basic Salary
        if (isNewEmployee) {
            JOptionPane.showMessageDialog(this, "This is a newly created employee and has no payroll records yet.");
        }
        
        jTextFieldEmpNum1.setText(employeeData[0]);
        jTextFieldFirstName1.setText(employeeData[2]);
        jTextFieldLastName1.setText(employeeData[1]);
        jTextFieldBirthDay1.setText(employeeData[3]);
        jTextAreaAddress1.setText(employeeData[4]); //
        jTextFieldPhoneNum1.setText(employeeData[5]);
        jTextFieldSSSNum1.setText(employeeData[6]);
        jTextFieldPhilHealthNum1.setText(employeeData[7]);
        jTextFieldTINNum1.setText(employeeData[8]);
        jTextFieldPagIBIGNum1.setText(employeeData[9]);
        jTextFieldStatus1.setText(employeeData[10]);
        jTextFieldPosition1.setText(employeeData[11]);
        jTextFieldSupervisor1.setText(employeeData[12]);
        jTextFieldBasicSalary1.setText(employeeData[13]);
        jTextFieldRiceSubsidy1.setText(employeeData[14]);
        jTextFieldPhoneAllowance1.setText(employeeData[15]);
        jTextFieldClothingAllowance1.setText(employeeData[16]);
        jTextFieldSemiMonthlyRate1.setText(employeeData[17]);
        jTextFieldHourlyRate1.setText(employeeData[18]);
        
        
    }

    public void calculatePayroll(Employee employee) {
    SalaryDeduction salaryDeduction = new SalaryDeduction();
     salaryDeduction.calculatePayroll(employee);

     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldEmpNum1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldLastName1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldFirstName1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldStatus1 = new javax.swing.JTextField();
        jTextFieldPosition1 = new javax.swing.JTextField();
        jTextFieldSupervisor1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldSSSNum1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextFieldPagIBIGNum1 = new javax.swing.JTextField();
        jTextFieldTINNum1 = new javax.swing.JTextField();
        jTextFieldPhilHealthNum1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextFieldBirthDay1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextFieldPhoneNum1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddress1 = new javax.swing.JTextArea();
        jComboBoxMonth1 = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextFieldBasicSalary1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextFieldRiceSubsidy1 = new javax.swing.JTextField();
        jTextFieldSemiMonthlyRate1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTextFieldHourlyRate1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldPhoneAllowance1 = new javax.swing.JTextField();
        jTextFieldClothingAllowance1 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextFieldSSSContribution1 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jTextFieldPhilHealthContribution1 = new javax.swing.JTextField();
        jTextFieldPagIBIGContribution1 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextFieldGrossPay1 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextFieldNetPay1 = new javax.swing.JTextField();
        jButtonCompute1 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonFileLeave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setText("MotorPH");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Payroll System");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 70));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Employee No. : ");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, 20));

        jTextFieldEmpNum1.setEditable(false);
        jTextFieldEmpNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpNum1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldEmpNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 50, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Last Name : ");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 20));

        jTextFieldLastName1.setEditable(false);
        jPanel3.add(jTextFieldLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("First Name :");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 20));

        jTextFieldFirstName1.setEditable(false);
        jPanel3.add(jTextFieldFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 140, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Address :");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 60, 20));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Status :");
        jPanel20.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 60, 20));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("Position :");
        jPanel20.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 90, 20));

        jTextFieldStatus1.setEditable(false);
        jPanel20.add(jTextFieldStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 140, -1));

        jTextFieldPosition1.setEditable(false);
        jPanel20.add(jTextFieldPosition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 140, -1));

        jTextFieldSupervisor1.setEditable(false);
        jPanel20.add(jTextFieldSupervisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 140, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("SSS No. :");
        jPanel20.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 60, 20));

        jTextFieldSSSNum1.setEditable(false);
        jPanel20.add(jTextFieldSSSNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 140, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("PhilHealth No. :");
        jPanel20.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 90, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("TIN :");
        jPanel20.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 60, 20));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("Pag-IBIG No. :");
        jPanel20.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 90, 20));

        jTextFieldPagIBIGNum1.setEditable(false);
        jPanel20.add(jTextFieldPagIBIGNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, 140, -1));

        jTextFieldTINNum1.setEditable(false);
        jPanel20.add(jTextFieldTINNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 140, -1));

        jTextFieldPhilHealthNum1.setEditable(false);
        jPanel20.add(jTextFieldPhilHealthNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 140, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("Immediate Supervisor :");
        jPanel20.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 130, 20));

        jTextFieldBirthDay1.setEditable(false);
        jPanel20.add(jTextFieldBirthDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 140, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("Birthday:");
        jPanel20.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jTextFieldPhoneNum1.setEditable(false);
        jPanel20.add(jTextFieldPhoneNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 140, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("Phone Number :");
        jPanel20.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 100, 20));

        jTextAreaAddress1.setEditable(false);
        jTextAreaAddress1.setColumns(20);
        jTextAreaAddress1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddress1);

        jPanel20.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 240, 40));

        jPanel3.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1260, 180));

        jComboBoxMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "November", "December" }));
        jComboBoxMonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonth1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxMonth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, 40));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setText("Select Month");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 20));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setText("Hourly Rate :");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, 20));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Gross Semi-Monthly Rate :");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 160, 20));

        jTextFieldBasicSalary1.setEditable(false);
        jPanel3.add(jTextFieldBasicSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 270, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Basic Salary :");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 100, 20));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Rice Subsidy :");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 90, 20));

        jTextFieldRiceSubsidy1.setEditable(false);
        jPanel3.add(jTextFieldRiceSubsidy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 270, -1));

        jTextFieldSemiMonthlyRate1.setEditable(false);
        jPanel3.add(jTextFieldSemiMonthlyRate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 270, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel52.setText("Total");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 100, 20));

        jTextFieldHourlyRate1.setEditable(false);
        jTextFieldHourlyRate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourlyRate1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldHourlyRate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 270, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel53.setText("Earnings");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 70, 20));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("Phone Allowance :");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 110, 20));

        jTextFieldPhoneAllowance1.setEditable(false);
        jPanel3.add(jTextFieldPhoneAllowance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 270, -1));

        jTextFieldClothingAllowance1.setEditable(false);
        jPanel3.add(jTextFieldClothingAllowance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 270, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Clothing Allowance :");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 140, 20));

        jTextFieldSSSContribution1.setEditable(false);
        jTextFieldSSSContribution1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSSSContribution1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldSSSContribution1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, 270, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel56.setText("SSS Contribution :");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 110, 20));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setText("PhilHealth Contribution :");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 140, 20));

        jTextFieldPhilHealthContribution1.setEditable(false);
        jTextFieldPhilHealthContribution1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhilHealthContribution1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldPhilHealthContribution1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 270, -1));

        jTextFieldPagIBIGContribution1.setEditable(false);
        jTextFieldPagIBIGContribution1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPagIBIGContribution1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldPagIBIGContribution1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 270, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("Pag-IBIG Contribution :");
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 150, 20));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel59.setText("Allowances");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, 20));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("Gross Pay :");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 100, 20));

        jTextFieldGrossPay1.setEditable(false);
        jPanel3.add(jTextFieldGrossPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 270, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setText("Net Pay :");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 100, 20));

        jTextFieldNetPay1.setEditable(false);
        jPanel3.add(jTextFieldNetPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 270, -1));

        jButtonCompute1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCompute1.setText("Compute");
        jButtonCompute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompute1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCompute1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, 170, 50));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel62.setText("Deductions");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 90, 20));

        jButtonBack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack1.setText("Log Out");
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 100, 30));

        jButtonFileLeave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFileLeave.setText("File Leave");
        jButtonFileLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileLeaveActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFileLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 620, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmpNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpNum1ActionPerformed

    private void jComboBoxMonth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonth1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonth1ActionPerformed

    private void jTextFieldHourlyRate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourlyRate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourlyRate1ActionPerformed

    private void jTextFieldSSSContribution1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSSSContribution1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSSSContribution1ActionPerformed

    private void jTextFieldPhilHealthContribution1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhilHealthContribution1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhilHealthContribution1ActionPerformed

    private void jTextFieldPagIBIGContribution1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPagIBIGContribution1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPagIBIGContribution1ActionPerformed

    private void jButtonCompute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompute1ActionPerformed
        //         double sssContribution = SalaryDeduction.getSSS(); // assuming getSSS() returns a numeric value

        //    jTextFieldSSSContribution.setText(String.valueOf(SalaryDeduction.getSSS()));
        //    jTextFieldPhilHealthContribution.setText(String.valueOf(SalaryDeduction.getPhilDeduct()));
        //    jTextFieldPagIBIGContribution.setText(String.valueOf(SalaryDeduction.getPagibigDeduct()));

        double hourlyRate=Double.parseDouble(jTextFieldHourlyRate1.getText());
        double monthlyValue;
        String month = (String) jComboBoxMonth1.getSelectedItem();

        switch(month){
            case "January":
            monthlyValue = 21;
            break;
            case "February":
            monthlyValue = 20;
            break;
            case "March":
            monthlyValue = 23;
            break;
            case "April":
            monthlyValue = 22;
            break;
            case "May":
            monthlyValue = 22;
            break;
            case "June":
            monthlyValue = 21;
            break;
            case "July":
            monthlyValue = 22;
            break;
            case "August":
            monthlyValue = 23;
            break;
            case "September":
            monthlyValue = 22;
            break;
            case "October":
            monthlyValue = 23;
            break;
            case "November":
            monthlyValue = 22;
            break;
            case "December":
            monthlyValue = 21;
            break;
            default:
            monthlyValue = 0; // set a default value if no month is selected
            break;

        }

        double dailyRate=hourlyRate*8;
        double basicSalary = dailyRate*monthlyValue;

        LocalDate birthdayDate;
        try {
            birthdayDate = LocalDate.parse(jTextFieldBirthDay1.getText().trim(), DateTimeFormatter.ISO_LOCAL_DATE);
        } catch (Exception ex) {
            try {
                birthdayDate = LocalDate.parse(jTextFieldBirthDay1.getText().trim(), DateTimeFormatter.ofPattern("MM/dd/yyyy"));
            } catch (Exception ex2) {
                birthdayDate = LocalDate.now();
            }
        }

        BigDecimal riceSubsidy;
        try { riceSubsidy = new BigDecimal(jTextFieldRiceSubsidy1.getText().trim()); } catch (Exception ex) { riceSubsidy = BigDecimal.ZERO; }
        BigDecimal phoneAllowance;
        try { phoneAllowance = new BigDecimal(jTextFieldPhoneAllowance1.getText().trim()); } catch (Exception ex) { phoneAllowance = BigDecimal.ZERO; }
        BigDecimal clothingAllowance;
        try { clothingAllowance = new BigDecimal(jTextFieldClothingAllowance1.getText().trim()); } catch (Exception ex) { clothingAllowance = BigDecimal.ZERO; }

        Employee employee = new Employee.Builder(
                jTextFieldEmpNum1.getText(),
                jTextFieldLastName1.getText(),
                jTextFieldFirstName1.getText(),
                birthdayDate
        )
                .withBasicSalary(BigDecimal.valueOf(basicSalary))
                .withRiceSubsidy(riceSubsidy)
                .withPhoneAllowance(phoneAllowance)
                .withClothingAllowance(clothingAllowance)
                .withHourlyRate(BigDecimal.valueOf(hourlyRate))
                .build();

        SalaryDeduction salaryDeduction = new SalaryDeduction();
        salaryDeduction.calculatePayroll(employee);

        jTextFieldSSSContribution1.setText(String.valueOf(salaryDeduction.getSSS()));
        jTextFieldPhilHealthContribution1.setText(String.valueOf(salaryDeduction.getPhilDeduct()));
        jTextFieldPagIBIGContribution1.setText(String.valueOf(salaryDeduction.getPagibigDeduct()));

        WithholdingTax withholdingtax = new WithholdingTax();
        withholdingtax.calculatePayroll(employee);

        TotalPay totalpay = new TotalPay();
        totalpay.calculatePayroll(employee, withholdingtax);
        jTextFieldNetPay1.setText(String.valueOf(totalpay.getNetPay()));
        jTextFieldGrossPay1.setText(String.valueOf(totalpay.getGross()));

        // JOptionPane.showMessageDialog();
    }//GEN-LAST:event_jButtonCompute1ActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        // + go back to login page
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jButtonFileLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileLeaveActionPerformed
        // TODO add your handling code here:
        UserAccount userAcc = new UserAccount();
        userAcc.setEmployeeID(jTextFieldEmpNum1.getText());
        new LeaveRequestForm(userAcc).setVisible(true);

    }//GEN-LAST:event_jButtonFileLeaveActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewEmployee().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonCompute1;
    private javax.swing.JButton jButtonFileLeave;
    private javax.swing.JComboBox<String> jComboBoxMonth1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaAddress1;
    private javax.swing.JTextField jTextFieldBasicSalary1;
    private javax.swing.JTextField jTextFieldBirthDay1;
    private javax.swing.JTextField jTextFieldClothingAllowance1;
    private javax.swing.JTextField jTextFieldEmpNum1;
    private javax.swing.JTextField jTextFieldFirstName1;
    private javax.swing.JTextField jTextFieldGrossPay1;
    private javax.swing.JTextField jTextFieldHourlyRate1;
    private javax.swing.JTextField jTextFieldLastName1;
    private javax.swing.JTextField jTextFieldNetPay1;
    private javax.swing.JTextField jTextFieldPagIBIGContribution1;
    private javax.swing.JTextField jTextFieldPagIBIGNum1;
    private javax.swing.JTextField jTextFieldPhilHealthContribution1;
    private javax.swing.JTextField jTextFieldPhilHealthNum1;
    private javax.swing.JTextField jTextFieldPhoneAllowance1;
    private javax.swing.JTextField jTextFieldPhoneNum1;
    private javax.swing.JTextField jTextFieldPosition1;
    private javax.swing.JTextField jTextFieldRiceSubsidy1;
    private javax.swing.JTextField jTextFieldSSSContribution1;
    private javax.swing.JTextField jTextFieldSSSNum1;
    private javax.swing.JTextField jTextFieldSemiMonthlyRate1;
    private javax.swing.JTextField jTextFieldStatus1;
    private javax.swing.JTextField jTextFieldSupervisor1;
    private javax.swing.JTextField jTextFieldTINNum1;
    // End of variables declaration//GEN-END:variables
}
