/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.LeaveManagement;

import Model.UserAccount;
import com.opencsv.CSVWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.Date;
import DAO.EmployeeCSVReader;

/**
 *
 * @author Aira Joie Piopongco
 */
public class LeaveRequestForm extends javax.swing.JFrame {
     private EmployeeCSVReader reader;
    private UserAccount userAccount;
      private List<String[]> leaveDataBase;
    /**
     * Creates new form LeaveRequestForm
     */
    public LeaveRequestForm(UserAccount userAcc) {
        initComponents();
        
        Date fromDate = jCalendarFrom.getDate();
    Date toDate = jCalendarTo.getDate();
         Calendar calendar = Calendar.getInstance();
         calendar.setTime(toDate);
         calendar.add(Calendar.DAY_OF_MONTH, 1);
     toDate = calendar.getTime();
     
    jCalendarTo.setDate(toDate);
        
        this.reader = new EmployeeCSVReader("MotorPH.csv");
        this.userAccount = userAcc;
        String employeeID = userAcc.getEmployeeID();
        String[] employeeData = reader.searchEmployee(employeeID);
        
        jTextFieldEmpNo.setText(employeeData[0]);
        jTextFieldFirstName.setText(employeeData[2]);
        jTextFieldLastName.setText(employeeData[1]);
         jTextFieldPosition.setText(employeeData[11]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmpNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonSubmitRequest = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxLeaveType = new javax.swing.JComboBox<>();
        jCalendarTo = new com.toedter.calendar.JCalendar();
        jCalendarFrom = new com.toedter.calendar.JCalendar();
        jTextFieldLastName = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Leave Request Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Employee #");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, 20));

        jTextFieldEmpNo.setEditable(false);
        jTextFieldEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpNoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 270, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 20));

        jTextFieldFirstName.setEditable(false);
        jPanel2.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 270, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 20));

        jTextFieldPosition.setEditable(false);
        jTextFieldPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPositionActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 270, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Position");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Leave Type");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Date of Return");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, 20));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Start of Leave");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 80, 20));

        jButtonSubmitRequest.setBackground(new java.awt.Color(0, 255, 204));
        jButtonSubmitRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSubmitRequest.setText("Submit Request");
        jButtonSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitRequestActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, 30));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Date");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 60, 20));

        jComboBoxLeaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation", "Sick" }));
        jPanel2.add(jComboBoxLeaveType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 270, -1));
        jPanel2.add(jCalendarTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 180, 110));
        jPanel2.add(jCalendarFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 180, 110));

        jTextFieldLastName.setEditable(false);
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, -1));

        jButtonBack.setBackground(new java.awt.Color(0, 255, 204));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitRequestActionPerformed
     // TODO add your handling code here:
                                                     
    // TODO add your handling code here:
reader = new EmployeeCSVReader("LeaveManagement.csv");
leaveDataBase = reader.getEmployeeData();

String empID = jTextFieldEmpNo.getText();

int newIndex = leaveDataBase.size() + 1;
        
String[] newRow = new String[9]; 
newRow[0] = String.valueOf(newIndex);
newRow[1] = jTextFieldEmpNo.getText();
newRow[2] = jTextFieldLastName.getText();
newRow[3] = jTextFieldFirstName.getText();
newRow[4] = jTextFieldPosition.getText();
newRow[5] = (String) jComboBoxLeaveType.getSelectedItem();
newRow[8] = "Pending";
    
   
    

// Validate dates
Date fromDate = jCalendarFrom.getDate();
Date toDate = jCalendarTo.getDate();
 
if(toDate.before(fromDate)) { // Check if to date is before from date
    JOptionPane.showMessageDialog(jButtonSubmitRequest, "End date cannot be before starting date");
} else {
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
    String from = sdf.format(fromDate);
    newRow[6] = from;

    if (toDate.equals(fromDate)) { // Check if to date is the same as from date
        toDate = new Date(toDate.getTime() + 86400000); // Increment to date by one day
    }
    String to = sdf.format(toDate);
    newRow[7] = to;

    // Add the new row to the leaveDataBase
    leaveDataBase.add(newRow);

    // Write the updated data to the CSV file
    try (CSVWriter writer = new CSVWriter(new FileWriter("LeaveManagement.csv", false), ',', '\u0000')) {
        for (String[] updatedRecord : leaveDataBase) {
            if (updatedRecord!= null && updatedRecord.length > 0) { // Check for empty rows
                writer.writeNext(updatedRecord);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(jButtonSubmitRequest, "Error writing to file: " + e.getMessage());
    }
    JOptionPane.showMessageDialog(jButtonSubmitRequest, "Request Submitted!");
    this.setVisible(false);
}
        
    }//GEN-LAST:event_jButtonSubmitRequestActionPerformed

    private void jTextFieldEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpNoActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPositionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LeaveRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LeaveRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LeaveRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LeaveRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LeaveRequestForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmitRequest;
    private com.toedter.calendar.JCalendar jCalendarFrom;
    private com.toedter.calendar.JCalendar jCalendarTo;
    private javax.swing.JComboBox<String> jComboBoxLeaveType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEmpNo;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPosition;
    // End of variables declaration//GEN-END:variables
}
